/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AddReferralData } from '../models/AddReferralData';
import { HttpFile } from '../http/http';

/**
* Fields for initiating a referral to a remote DSSA via /referrals/add
*/
export class AddReferralRequestBody {
    /**
    * UUIDv4 of the remote DSSA the referral is being made to
    */
    'remoteDssaUuid': string;
    /**
    * Whether the member is present to complete the FTC flow. If true, an FTC URL is returned for immediate redirect. If false, a notification is sent to the member.
    */
    'memberPresent': boolean;
    /**
    * URL the member is redirected to after completing the FTC flow
    */
    'returnTo': string;
    'referralData': AddReferralData;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "remoteDssaUuid",
            "baseName": "remote_dssa_uuid",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "memberPresent",
            "baseName": "member_present",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "returnTo",
            "baseName": "return_to",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "referralData",
            "baseName": "referral_data",
            "type": "AddReferralData",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AddReferralRequestBody.attributeTypeMap;
    }

    public constructor() {
    }
}
