/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Response from creating a referral via /referrals/add. The shape varies depending on member connection status: \'complete\' when the member is already connected to the remote DSSA, \'pending\' with url/qr when the member is present but not connected, and \'pending\' with message when the member is not present and has been notified.
*/
export class AddReferralResponse {
    /**
    * Indicates success
    */
    'success'?: number;
    /**
    * \'complete\' when the member is already connected to the remote DSSA; \'pending\' when the member needs to complete the FTC flow
    */
    'status'?: AddReferralResponseStatusEnum;
    /**
    * Present only when status is \'pending\'. Describes the pending action taken.
    */
    'message'?: string;
    /**
    * FTC URL the member should be redirected to. Present only when status is \'pending\' and member_present is true.
    */
    'url'?: string;
    /**
    * QR code data URI for the FTC URL. Present only when status is \'pending\' and member_present is true.
    */
    'qr'?: string;
    /**
    * ID of the newly created referral
    */
    'referralId'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "AddReferralResponseStatusEnum",
            "format": ""
        },
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "qr",
            "baseName": "qr",
            "type": "string",
            "format": ""
        },
        {
            "name": "referralId",
            "baseName": "referral_id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AddReferralResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum AddReferralResponseStatusEnum {
    Complete = 'complete',
    Pending = 'pending',
    UnknownDefaultOpenApi = '11184809'
}

