/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AuthErrorResponseError } from '../models/AuthErrorResponseError';
import { HttpFile } from '../http/http';

export class AuthErrorResponse {
    'error'?: AuthErrorResponseError;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "error",
            "baseName": "error",
            "type": "AuthErrorResponseError",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AuthErrorResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
