/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Fields for creating a generic calendar event
*/
export class CalendarEventCreateRequestBody {
    /**
    * Title of the event
    */
    'title': string;
    /**
    * Detailed description of the event
    */
    'description'?: string;
    /**
    * Start date and time as Unix timestamp
    */
    'startTimestamp': number;
    /**
    * End date and time as Unix timestamp
    */
    'endTimestamp': number;
    /**
    * Status of the event
    */
    'status': CalendarEventCreateRequestBodyStatusEnum;
    /**
    * Creator of the event
    */
    'organiser'?: string;
    /**
    * Person attending the event
    */
    'attendee'?: string;
    /**
    * Event location
    */
    'location'?: string;
    /**
    * Type of event
    */
    'type'?: CalendarEventCreateRequestBodyTypeEnum | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTimestamp",
            "baseName": "start_timestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "endTimestamp",
            "baseName": "end_timestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CalendarEventCreateRequestBodyStatusEnum",
            "format": ""
        },
        {
            "name": "organiser",
            "baseName": "organiser",
            "type": "string",
            "format": ""
        },
        {
            "name": "attendee",
            "baseName": "attendee",
            "type": "string",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "CalendarEventCreateRequestBodyTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CalendarEventCreateRequestBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CalendarEventCreateRequestBodyStatusEnum {
    Invited = 'INVITED',
    Tentative = 'TENTATIVE',
    Confirmed = 'CONFIRMED',
    Rejected = 'REJECTED',
    Cancelled = 'CANCELLED',
    UnknownDefaultOpenApi = '11184809'
}
export enum CalendarEventCreateRequestBodyTypeEnum {
    Appointment = 'Appointment',
    UnknownDefaultOpenApi = '11184809'
}

