/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A calendar event returned from the API
*/
export class CalendarEvent {
    'id'?: string;
    'instance'?: string;
    'source'?: string;
    'createdTimestamp'?: string;
    'updatedTimestamp'?: string;
    'externalUid'?: string | null;
    'title'?: string | null;
    'description'?: string | null;
    'startTimestamp'?: string;
    'endTimestamp'?: string;
    'organiser'?: string | null;
    'attendee'?: string | null;
    'status'?: string | null;
    'location'?: string | null;
    'type'?: string | null;
    'tags'?: string | null;
    'trigger'?: string | null;
    'action'?: string | null;
    'reminderDescription'?: string | null;
    'contextName'?: string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "instance",
            "baseName": "instance",
            "type": "string",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdTimestamp",
            "baseName": "created_timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedTimestamp",
            "baseName": "updated_timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalUid",
            "baseName": "external_uid",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTimestamp",
            "baseName": "start_timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "endTimestamp",
            "baseName": "end_timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "organiser",
            "baseName": "organiser",
            "type": "string",
            "format": ""
        },
        {
            "name": "attendee",
            "baseName": "attendee",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "string",
            "format": ""
        },
        {
            "name": "trigger",
            "baseName": "trigger",
            "type": "string",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "reminderDescription",
            "baseName": "reminder_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "contextName",
            "baseName": "context_name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CalendarEvent.attributeTypeMap;
    }

    public constructor() {
    }
}
