/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Fields for creating a calendar event of type \'Appointment\'
*/
export class CalendarAppointmentCreateRequestBody {
    /**
    * Title of the event
    */
    'title': string;
    /**
    * Detailed description of the event
    */
    'description'?: string;
    /**
    * Start date and time as Unix timestamp
    */
    'startTimestamp': number;
    /**
    * End date and time as Unix timestamp
    */
    'endTimestamp': number;
    /**
    * Status of the event
    */
    'status': CalendarAppointmentCreateRequestBodyStatusEnum;
    /**
    * Creator of the event
    */
    'organiser'?: string;
    /**
    * Person attending the event
    */
    'attendee'?: string;
    /**
    * Event location
    */
    'location'?: string;
    /**
    * The context the appointment belongs to e.g. a referral
    */
    'context': CalendarAppointmentCreateRequestBodyContextEnum;
    /**
    * The id of the specific context record that this appointment relates to e.g. the referral id
    */
    'contextId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTimestamp",
            "baseName": "start_timestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "endTimestamp",
            "baseName": "end_timestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CalendarAppointmentCreateRequestBodyStatusEnum",
            "format": ""
        },
        {
            "name": "organiser",
            "baseName": "organiser",
            "type": "string",
            "format": ""
        },
        {
            "name": "attendee",
            "baseName": "attendee",
            "type": "string",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "context",
            "baseName": "context",
            "type": "CalendarAppointmentCreateRequestBodyContextEnum",
            "format": ""
        },
        {
            "name": "contextId",
            "baseName": "context_id",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CalendarAppointmentCreateRequestBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum CalendarAppointmentCreateRequestBodyStatusEnum {
    Invited = 'INVITED',
    Tentative = 'TENTATIVE',
    Confirmed = 'CONFIRMED',
    Rejected = 'REJECTED',
    Cancelled = 'CANCELLED',
    UnknownDefaultOpenApi = '11184809'
}
export enum CalendarAppointmentCreateRequestBodyContextEnum {
    Referral = 'referral',
    UnknownDefaultOpenApi = '11184809'
}

