/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ReferralSingleResponseReferral {
    'id'?: number;
    /**
    * A UUIDv4 that uniquely identifies the service this referral relates to
    */
    'serviceIdentifier'?: string;
    'createdTimestamp'?: number;
    'serviceId'?: number;
    'type'?: string;
    'status'?: ReferralSingleResponseReferralStatusEnum;
    'memo'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "serviceIdentifier",
            "baseName": "service_identifier",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "createdTimestamp",
            "baseName": "created_timestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "serviceId",
            "baseName": "service_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ReferralSingleResponseReferralStatusEnum",
            "format": ""
        },
        {
            "name": "memo",
            "baseName": "memo",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReferralSingleResponseReferral.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ReferralSingleResponseReferralStatusEnum {
    Referred = 'Referred',
    InProgress = 'In Progress',
    Accepted = 'Accepted',
    Rejected = 'Rejected',
    UnknownDefaultOpenApi = '11184809'
}

