/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ReferralCommonRequestBodyFieldsReferreeAvailability } from '../models/ReferralCommonRequestBodyFieldsReferreeAvailability';
import { HttpFile } from '../http/http';

/**
* Common fields shared across all referral types
*/
export class ReferralCommonRequestBodyFields {
    /**
    * ID of the service being referred to
    */
    'serviceId'?: number;
    /**
    * A UUIDv4 that uniquely identifies the service this referral relates to
    */
    'serviceIdentifier'?: string;
    /**
    * Background information about the referree
    */
    'referreeBackground'?: string;
    /**
    * Requirements of the referree
    */
    'referreeRequirements'?: string;
    'referreeAvailability'?: ReferralCommonRequestBodyFieldsReferreeAvailability;
    /**
    * Name of the person making the referral
    */
    'referrerName'?: string;
    /**
    * Name of the service
    */
    'serviceName'?: string;
    /**
    * Description of the service
    */
    'serviceDescription'?: string;
    /**
    * URL of the service
    */
    'serviceUrl'?: string;
    /**
    * Email address of the service
    */
    'serviceEmail'?: string;
    /**
    * Contact number for the service
    */
    'contactNumber'?: string;
    /**
    * Internal memo or notes
    */
    'memo'?: string;
    /**
    * Start time as a Unix timestamp
    */
    'startTime'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "serviceId",
            "baseName": "service_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "serviceIdentifier",
            "baseName": "service_identifier",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "referreeBackground",
            "baseName": "referree_background",
            "type": "string",
            "format": ""
        },
        {
            "name": "referreeRequirements",
            "baseName": "referree_requirements",
            "type": "string",
            "format": ""
        },
        {
            "name": "referreeAvailability",
            "baseName": "referree_availability",
            "type": "ReferralCommonRequestBodyFieldsReferreeAvailability",
            "format": ""
        },
        {
            "name": "referrerName",
            "baseName": "referrer_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceName",
            "baseName": "service_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceDescription",
            "baseName": "service_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceUrl",
            "baseName": "service_url",
            "type": "string",
            "format": "uri"
        },
        {
            "name": "serviceEmail",
            "baseName": "service_email",
            "type": "string",
            "format": "email"
        },
        {
            "name": "contactNumber",
            "baseName": "contact_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "memo",
            "baseName": "memo",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return ReferralCommonRequestBodyFields.attributeTypeMap;
    }

    public constructor() {
    }
}
