/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Availability of the referree. If not provided, defaults to empty AM/PM arrays.
*/
export class ReferralCommonRequestBodyFieldsReferreeAvailability {
    /**
    * Morning availability slots
    */
    'AM'?: Array<string>;
    /**
    * Afternoon availability slots
    */
    'PM'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "AM",
            "baseName": "AM",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "PM",
            "baseName": "PM",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReferralCommonRequestBodyFieldsReferreeAvailability.attributeTypeMap;
    }

    public constructor() {
    }
}
