/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Fields for updating the status of a referral (e.g. from \'Referred\' to \'Accepted\')
*/
export class ReferralStatusUpdateRequestBody {
    /**
    * ID of the referral to be updated
    */
    'id': number;
    /**
    * Status the referral is to be updated to
    */
    'status': ReferralStatusUpdateRequestBodyStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ReferralStatusUpdateRequestBodyStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ReferralStatusUpdateRequestBody.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ReferralStatusUpdateRequestBodyStatusEnum {
    Referred = 'Referred',
    InProgress = 'In Progress',
    Accepted = 'Accepted',
    Rejected = 'Rejected',
    UnknownDefaultOpenApi = '11184809'
}

