/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SecureMessageCommonFields {
    /**
    * Content of the message
    */
    'messageContent': string;
    /**
    * ID of the conversation formatted like {context}-{context_id} where context is e.g. \'referral\' and context_id is the id of the specifc record in that context.
    */
    'conversationId': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messageContent",
            "baseName": "message_content",
            "type": "string",
            "format": ""
        },
        {
            "name": "conversationId",
            "baseName": "conversation_id",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SecureMessageCommonFields.attributeTypeMap;
    }

    public constructor() {
    }
}
