/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SecureMessage } from '../models/SecureMessage';
import { HttpFile } from '../http/http';

/**
* Response containing all messages in a conversation
*/
export class SecureMessageConversationResponse {
    'messages'?: Array<SecureMessage>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "messages",
            "baseName": "messages",
            "type": "Array<SecureMessage>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SecureMessageConversationResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
