/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A single message within a conversation
*/
export class SecureMessage {
    /**
    * Message ID
    */
    'id'?: string;
    /**
    * Conversation identifier
    */
    'conversationId'?: string;
    /**
    * Recipient of the message (present on sent messages)
    */
    'messageTo'?: string;
    /**
    * Sender of the message (present on received messages)
    */
    'messageFrom'?: string;
    /**
    * Timestamp when message was sent
    */
    'timeSent'?: string;
    /**
    * Timestamp when message was received
    */
    'timeReceived'?: string;
    /**
    * Content of the message
    */
    'messageContent'?: string;
    /**
    * A UUIDv4 that uniquely identifies the service this message relates to, if one was provided
    */
    'serviceIdentifier'?: string;
    /**
    * Message status
    */
    'status'?: SecureMessageStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "conversationId",
            "baseName": "conversation_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageTo",
            "baseName": "message_to",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageFrom",
            "baseName": "message_from",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeSent",
            "baseName": "time_sent",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeReceived",
            "baseName": "time_received",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageContent",
            "baseName": "message_content",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceIdentifier",
            "baseName": "service_identifier",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SecureMessageStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SecureMessage.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum SecureMessageStatusEnum {
    Sent = 'sent',
    Received = 'received',
    UnknownDefaultOpenApi = '11184809'
}

