/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimelineResponseTimelineInner } from '../models/TimelineResponseTimelineInner';
import { HttpFile } from '../http/http';

/**
* Response containing a mixed timeline of calendar events, referrals, and secure messages
*/
export class TimelineResponse {
    'success'?: number;
    /**
    * Array of timeline items, which can be calendar events, referrals, or secure messages
    */
    'timeline'?: Array<TimelineResponseTimelineInner>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "success",
            "baseName": "success",
            "type": "number",
            "format": ""
        },
        {
            "name": "timeline",
            "baseName": "timeline",
            "type": "Array<TimelineResponseTimelineInner>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TimelineResponse.attributeTypeMap;
    }

    public constructor() {
    }
}
