/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimelineResponseTimelineInnerOneOf } from '../models/TimelineResponseTimelineInnerOneOf';
import { TimelineResponseTimelineInnerOneOf1 } from '../models/TimelineResponseTimelineInnerOneOf1';
import { TimelineResponseTimelineInnerOneOf2 } from '../models/TimelineResponseTimelineInnerOneOf2';
import { HttpFile } from '../http/http';

/**
 * @type TimelineResponseTimelineInner
 * Type
 * @export
 */
export type TimelineResponseTimelineInner = TimelineResponseTimelineInnerOneOf | TimelineResponseTimelineInnerOneOf1 | TimelineResponseTimelineInnerOneOf2;

/**
* @type TimelineResponseTimelineInnerClass
* @export
*/
export class TimelineResponseTimelineInnerClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


