/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Referral item
*/
export class TimelineResponseTimelineInnerOneOf {
    'id'?: number;
    'featureBlock'?: string;
    'featureBlockId'?: string;
    'startTimestamp'?: string;
    'itemTimestamp'?: number;
    'serviceDescription'?: string;
    'serviceName'?: string;
    'contactName'?: string;
    'contactTitle'?: string;
    'memo'?: string;
    'status'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "featureBlock",
            "baseName": "feature_block",
            "type": "string",
            "format": ""
        },
        {
            "name": "featureBlockId",
            "baseName": "feature_block_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTimestamp",
            "baseName": "start_timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemTimestamp",
            "baseName": "item_timestamp",
            "type": "number",
            "format": ""
        },
        {
            "name": "serviceDescription",
            "baseName": "service_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceName",
            "baseName": "service_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "contactName",
            "baseName": "contact_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "contactTitle",
            "baseName": "contact_title",
            "type": "string",
            "format": ""
        },
        {
            "name": "memo",
            "baseName": "memo",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TimelineResponseTimelineInnerOneOf.attributeTypeMap;
    }

    public constructor() {
    }
}
