/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Calendar event item
*/
export class TimelineResponseTimelineInnerOneOf2 {
    'id'?: number;
    'featureBlock'?: string;
    'featureBlockId'?: string;
    'startTimestamp'?: string;
    'itemTimestamp'?: number;
    'endTimestamp'?: string;
    'title'?: string;
    'location'?: string;
    'organiser'?: string;
    'description'?: string;
    'status'?: string;
    'durationString'?: string;
    'durationOfEvent'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "featureBlock",
            "baseName": "feature_block",
            "type": "string",
            "format": ""
        },
        {
            "name": "featureBlockId",
            "baseName": "feature_block_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTimestamp",
            "baseName": "start_timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemTimestamp",
            "baseName": "item_timestamp",
            "type": "number",
            "format": ""
        },
        {
            "name": "endTimestamp",
            "baseName": "end_timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "title",
            "baseName": "title",
            "type": "string",
            "format": ""
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "string",
            "format": ""
        },
        {
            "name": "organiser",
            "baseName": "organiser",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "durationString",
            "baseName": "duration_string",
            "type": "string",
            "format": ""
        },
        {
            "name": "durationOfEvent",
            "baseName": "duration_of_event",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TimelineResponseTimelineInnerOneOf2.attributeTypeMap;
    }

    public constructor() {
    }
}
