/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A single timeline item representing a secure message
*/
export class TimelineItemSecureMessage {
    /**
    * Type of feature block this timeline item belongs to
    */
    'featureBlock'?: string;
    /**
    * ID of the feature block
    */
    'featureBlockId'?: number;
    /**
    * Formatted start timestamp for display
    */
    'startTimestamp'?: string;
    /**
    * Raw timestamp of the timeline item
    */
    'itemTimestamp'?: number;
    'createdTimestamp'?: number;
    'updatedTimestamp'?: number;
    /**
    * Conversation identifier
    */
    'conversationId'?: string;
    /**
    * Timestamp when message was sent
    */
    'timeSent'?: string;
    /**
    * Timestamp when message was received
    */
    'timeReceived'?: string;
    /**
    * Sender of the message (present on received messages)
    */
    'messageFrom'?: string;
    /**
    * Recipient of the message (present on sent messages)
    */
    'messageTo'?: string;
    /**
    * Content of the message
    */
    'messageContent'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "featureBlock",
            "baseName": "feature_block",
            "type": "string",
            "format": ""
        },
        {
            "name": "featureBlockId",
            "baseName": "feature_block_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "startTimestamp",
            "baseName": "start_timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemTimestamp",
            "baseName": "item_timestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "createdTimestamp",
            "baseName": "created_timestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "updatedTimestamp",
            "baseName": "updated_timestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "conversationId",
            "baseName": "conversation_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeSent",
            "baseName": "time_sent",
            "type": "string",
            "format": ""
        },
        {
            "name": "timeReceived",
            "baseName": "time_received",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageFrom",
            "baseName": "message_from",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageTo",
            "baseName": "message_to",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageContent",
            "baseName": "message_content",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TimelineItemSecureMessage.attributeTypeMap;
    }

    public constructor() {
    }
}
