/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TimelineItemCalendarEvent } from '../models/TimelineItemCalendarEvent';
import { TimelineItemReferral } from '../models/TimelineItemReferral';
import { TimelineItemSecureMessage } from '../models/TimelineItemSecureMessage';
import { HttpFile } from '../http/http';

/**
* The timeline item, which can be one of multiple types, returned as an object
*/
/**
 * @type TimelineSingleItemResponseTimelineItem
 * Type
 * @export
 */
export type TimelineSingleItemResponseTimelineItem = TimelineItemCalendarEvent | TimelineItemReferral | TimelineItemSecureMessage;

/**
* @type TimelineSingleItemResponseTimelineItemClass
    * The timeline item, which can be one of multiple types, returned as an object
* @export
*/
export class TimelineSingleItemResponseTimelineItemClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}


