/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* A single timeline item representing a referral
*/
export class TimelineItemReferral {
    /**
    * Type of feature block this timeline item belongs to
    */
    'featureBlock'?: string;
    /**
    * ID of the feature block record i.e. the referral id
    */
    'featureBlockId'?: number;
    'instance'?: string;
    /**
    * The context within which this record was created i.e. the specific connection
    */
    'source'?: string;
    'createdTimestamp'?: number;
    'updatedTimestamp'?: number;
    /**
    * The id of the service that the referral relates to
    */
    'serviceId'?: number;
    'serviceName'?: string;
    'serviceDescription'?: string;
    'serviceUrl'?: string;
    'serviceEmail'?: string;
    'contactName'?: string;
    'contactTitle'?: string;
    'contactNumber'?: string;
    'referrerName'?: string;
    'status'?: TimelineItemReferralStatusEnum;
    'externalId'?: string;
    'startTime'?: number;
    'endTime'?: number;
    'isProcessed'?: boolean;
    'completeTime'?: number;
    'memo'?: string;
    'duration'?: string;
    'referreeBackground'?: string;
    'referreeRequirements'?: string;
    /**
    * Availability of the referree in AM/PM slots
    */
    'referreeAvailability'?: any;
    'type'?: string;
    'startTimestamp'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "featureBlock",
            "baseName": "feature_block",
            "type": "string",
            "format": ""
        },
        {
            "name": "featureBlockId",
            "baseName": "feature_block_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "instance",
            "baseName": "instance",
            "type": "string",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string",
            "format": ""
        },
        {
            "name": "createdTimestamp",
            "baseName": "created_timestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "updatedTimestamp",
            "baseName": "updated_timestamp",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "serviceId",
            "baseName": "service_id",
            "type": "number",
            "format": ""
        },
        {
            "name": "serviceName",
            "baseName": "service_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceDescription",
            "baseName": "service_description",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceUrl",
            "baseName": "service_url",
            "type": "string",
            "format": ""
        },
        {
            "name": "serviceEmail",
            "baseName": "service_email",
            "type": "string",
            "format": ""
        },
        {
            "name": "contactName",
            "baseName": "contact_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "contactTitle",
            "baseName": "contact_title",
            "type": "string",
            "format": ""
        },
        {
            "name": "contactNumber",
            "baseName": "contact_number",
            "type": "string",
            "format": ""
        },
        {
            "name": "referrerName",
            "baseName": "referrer_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TimelineItemReferralStatusEnum",
            "format": ""
        },
        {
            "name": "externalId",
            "baseName": "external_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "start_time",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "endTime",
            "baseName": "end_time",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "isProcessed",
            "baseName": "is_processed",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "completeTime",
            "baseName": "complete_time",
            "type": "number",
            "format": ""
        },
        {
            "name": "memo",
            "baseName": "memo",
            "type": "string",
            "format": ""
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "string",
            "format": ""
        },
        {
            "name": "referreeBackground",
            "baseName": "referree_background",
            "type": "string",
            "format": ""
        },
        {
            "name": "referreeRequirements",
            "baseName": "referree_requirements",
            "type": "string",
            "format": ""
        },
        {
            "name": "referreeAvailability",
            "baseName": "referree_availability",
            "type": "any",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTimestamp",
            "baseName": "start_timestamp",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TimelineItemReferral.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum TimelineItemReferralStatusEnum {
    Referred = 'Referred',
    InProgress = 'In Progress',
    Accepted = 'Accepted',
    Rejected = 'Rejected',
    UnknownDefaultOpenApi = '11184809'
}

