/**
 * PDX API
 * API for processing subscribers requests to the PDX API to retrieve one or more combinations of data, deliver and update records in a Members PDS and ensure record integrity is maintained.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Secure message item
*/
export class TimelineResponseTimelineInnerOneOf1 {
    'id'?: number;
    'featureBlock'?: string;
    'featureBlockId'?: string;
    'startTimestamp'?: string;
    'itemTimestamp'?: number;
    'createdTimestamp'?: number;
    'messageFrom'?: string;
    'messageTo'?: string;
    'messageContent'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "featureBlock",
            "baseName": "feature_block",
            "type": "string",
            "format": ""
        },
        {
            "name": "featureBlockId",
            "baseName": "feature_block_id",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTimestamp",
            "baseName": "start_timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "itemTimestamp",
            "baseName": "item_timestamp",
            "type": "number",
            "format": ""
        },
        {
            "name": "createdTimestamp",
            "baseName": "created_timestamp",
            "type": "number",
            "format": ""
        },
        {
            "name": "messageFrom",
            "baseName": "message_from",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageTo",
            "baseName": "message_to",
            "type": "string",
            "format": ""
        },
        {
            "name": "messageContent",
            "baseName": "message_content",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TimelineResponseTimelineInnerOneOf1.attributeTypeMap;
    }

    public constructor() {
    }
}
